### ISSUE TITLE
.Net project appears incompletely committed (and incomplete!)

### ISSUE THREAD

**Issue by Ozzard** [SubhenduShekhar/cjson#78]
AssemblyInfo.cs appears in the .csproj but is not in the repo.  Is this expected?

Also, there appear to be utilities but the main body of the project is missing.  How's the port going, and do you want a hand?

**Comment by SubhenduShekhar** [comment]
@Ozzard working on it...
If you can help on python for some underlying issues will be helpful.

Let me know if you can contribute

**Comment by SubhenduShekhar** [comment]
@Ozzard this is implemented now.
